# Generated by Django 3.0.7 on 2020-06-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_passp_id', models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Номер паспорта')),
                ('client_surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('client_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('client_patronymic', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Очество')),
                ('client_gender', models.CharField(choices=[('W', 'Женский'), ('M', 'Мужской')], default='', max_length=1, verbose_name='Пол')),
                ('client_birthday', models.DateField(default='', verbose_name='Дата рожления')),
                ('client_address', models.TextField(default='', verbose_name='Адрес')),
                ('client_phone_number', models.CharField(default='', max_length=13, verbose_name='Номер телефона')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Адресс электронной почты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('visa_id', models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Номер визы')),
                ('visa_date_issue', models.DateField(default='', verbose_name='Дата выдачи')),
                ('visa_duration', models.SmallIntegerField(default='', verbose_name='Длительность')),
                ('visa_begin', models.DateField(default='', verbose_name='Дата начала визы')),
                ('visa_end', models.DateField(default='', verbose_name='Дата окончания визы')),
                ('visa_type', models.CharField(default='', help_text='Выберите одно значение', max_length=30, verbose_name='Тип визы')),
                ('visa_quantity_trip', models.CharField(choices=[('1', 'Однократная'), ('2', 'Двукратная'), ('M', 'Многократная')], default='', max_length=1, verbose_name='Кратность визы')),
                ('client_passp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
                'db_table': 'visa',
            },
        ),
    ]
