# Generated by Django 3.0.7 on 2020-06-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='client_passp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='ФИО'),
        ),
    ]
