# Generated by Django 3.0.7 on 2020-06-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20200607_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
    ]
