# Generated by Django 3.0.7 on 2020-06-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Код продажи')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('client_passp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sale',
            },
        ),
    ]
