# Generated by Django 3.0.7 on 2020-06-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200607_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('can_open_reports', 'Доступ к отчетам'),), 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
    ]
